apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemacpool-cert-manager
  namespace: {{ .Values.namespace }}
  labels:
    app: kubemacpool
    control-plane: cert-manager
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      control-plane: cert-manager
  template:
    metadata:
      labels:
        app: kubemacpool
        control-plane: cert-manager
    spec:
      serviceAccountName: kubemacpool
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      terminationGracePeriodSeconds: 5
      {{- include "kubevirt-stack.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: manager
          image: {{ include "kubevirt-stack.image" (dict "repository" .Values.image.repository "tag" .Values.image.tag "global" .Values.global) }}
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --v=production
          env:
            - name: RUN_CERT_MANAGER
              value: ""
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CA_ROTATE_INTERVAL
              value: {{ .Values.certManager.caRotateInterval | quote }}
            - name: CA_OVERLAP_INTERVAL
              value: {{ .Values.certManager.caOverlapInterval | quote }}
            - name: CERT_ROTATE_INTERVAL
              value: {{ .Values.certManager.certRotateInterval | quote }}
            - name: CERT_OVERLAP_INTERVAL
              value: {{ .Values.certManager.certOverlapInterval | quote }}
          resources:
            requests:
              cpu: 30m
              memory: 30Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        runAsNonRoot: true
        runAsUser: 107
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        {{- include "kubevirt-stack.nodeSelector" (dict "global" .Values.global.nodeSelector "local" .Values.nodeSelector) | nindent 8 }}
      {{- $tolerations := include "kubevirt-stack.tolerations" (dict "global" .Values.global.tolerations "local" .Values.tolerations) -}}
      {{- if $tolerations }}
      tolerations:
        {{- $tolerations | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: kubemacpool-service
  namespace: {{ .Values.namespace }}
  labels:
    app: kubemacpool
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 8000
      protocol: TCP
  selector:
    control-plane: mac-controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kubemacpool-mutator
  labels:
    app: kubemacpool
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
webhooks:
  - name: mutatepods.kubemacpool.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kubemacpool-service
        namespace: {{ .Values.namespace }}
        path: /mutate-pods
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
        - key: mutatepods.kubemacpool.io
          operator: In
          values:
            - allocate
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: NoneOnDryRun
  - name: mutatevirtualmachines.kubemacpool.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kubemacpool-service
        namespace: {{ .Values.namespace }}
        path: /mutate-virtualmachines
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
        - key: mutatevirtualmachines.kubemacpool.io
          operator: NotIn
          values:
            - ignore
    rules:
      - apiGroups:
          - kubevirt.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - virtualmachines
    sideEffects: NoneOnDryRun
