global:
  imageRegistry: ""
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []

namespace: kube-system

image:
  repository: ghcr.io/k8snetworkplumbingwg/whereabouts
  tag: v0.9.4

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi

tolerations:
  - operator: Exists
    effect: NoSchedule

nodeSelector: {}
priorityClassName: system-node-critical

cniConf:
  confDir: /etc/cni/net.d
  binDir: /opt/cni/bin

cronExpression: "30 4 * * *"

reconciler:
  enabled: true
  logLevel: debug
  priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 50Mi

nodeSliceController:
  enabled: true
  priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 50Mi
