global:
  imageRegistry: ""
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []

namespace: aaq
version: v1.7.0

operator:
  image:
    repository: quay.io/kubevirt/aaq-operator
  replicas: 1
  resources: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""

cr:
  imagePullPolicy: IfNotPresent
  ## PriorityClass applied to the whole AAQ control plane (aaq-server, aaq-controller).
  priorityClass: ""
  infra:
    nodeSelector:
      kubernetes.io/os: linux
  workload:
    nodeSelector:
      kubernetes.io/os: linux
