global:
  imageRegistry: ""
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []

namespace: kubevirt-ipam-controller-system
replicas: 2

image:
  repository: ghcr.io/kubevirt/ipam-controller
  tag: v0.6.1

resources:
  requests:
    cpu: 10m
    memory: 128Mi

nodeSelector: {}
tolerations: []
priorityClassName: kubevirt-cluster-critical

certManager:
  reloader: true
  issuer:
    name: ""
    kind: Issuer
    group: cert-manager.io
